# -*- coding: utf-8 -*-
"""Лабораторная работа 1 Павленко А.Х ПИ-311

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tzwfxwbNCc3mb3rsNaH3PlXVmEaxCbIy
"""

print("hello world")

"""1. Задание"""

a=int(input())
h=5
S=1/2*a*h
print(S)

x=((a**2)+(b**2)-(c**3))/2
print(x)

"""Уравнение


"""

a=5
b=int(input())
x=(a*b)
print(x)

"""Самостоятельное задание 1"""

a=5
b=int(input())
c=a+b
print(c)

"""Задание 2"""

a=int(input())
b=int(input())
z=(a+b)**2
print(z)

"""Задание 3"""

a=15
b=10
c=int(input())
v=(a+b)/c
print(v)

"""Задание 4"""

a=int(input())
b=int(input())
print("",a,"^2+2*",a,"^",b+b,"2")
print(a**2+2*a*b+b**2)

"""Задание 5"""

a=int(input())
b=int(input())
c=int(input())
p=(a+b+c)/2
P2=(a+b+c)
S=(p*(p-a)*(p-b)*(p-c))**0.5
print(P2)
print(S)

"""Задание 6"""

a=int(input())
b=int(input())
c=((a**3+14)/5)*b
print(c)

"""Задание 7"""

a=int(input())
n=int(input())
z=(a**2)/n
print(int(z))

"""Задание 8

"""

a=float(input("nim1 "))
b=float(input("nim2 "))
c=int(input("nim3 "))
z=int(input("nim4 "))
x=int(input("nim5 "))
v=int(input("nim6 "))
ab=a//b
cz=c*z
xv=x%v


print(int(ab))
print(cz)
print(xv)

"""Задание повышенной сложности №1

"""

n=int(input())
m=n/60
if m>=60:
  h=(n/60)//60
  m=((h*60)-m//1)*(-1)
if h>=24:
  d=h//24
  h=((d*24)-h)*(-1)
print("минут=",m)
print("часов=",h)
print("дней=",d)

"""Задание повышенной сложности №2"""

n=int(input("Введите число n: "))
N=str(n)
n2=N+N
n3=N+N+N
s=n+int(n2)+int(n3)
print("Результат равен:",s)