# -*- coding: utf-8 -*-
"""Лабораторная №4 Павленко А.Х ПИ-311

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-ECtOaqHt6uS0rqGsc8jMGpxGO_ReiZ
"""

